import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Software Sparks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main  className={styles.container}> 
        <div className='text-3xl'>
          <div className='text-center grid grid-cols-3 gap-4'>
            <div className={styles.gridcontainer}>
              <h1 className={styles.heading}>
                Create the unfathomable
              </h1>
              <p className={styles.content}>
                Create porjects that will change the world... Never underestimate the power of a single `Hello World`. This project aims to show developers they are not limited by their skill level. Just hit create new project if you get stuck the classes are there to help.
              </p>
              <button className={styles.button}>Learn more...</button>
            </div>
            <div className={styles.gridcontainer}>
              <h1 className={styles.heading}>
                No limits in development
              </h1>
              <p className={styles.content}>
                Our new code editing expirence will change the speed in which you code. No more waiting for the compiler.
              </p>
              <button className={styles.button}>Learn more...</button>
            </div>
            <div className={styles.gridcontainer}>
              <h1 className={styles.heading}>
                Understand at a high level
              </h1>
              <p className={styles.content}>
                Our available classes allow you to understand the programming language at a high level.
              </p>
              <button className={styles.button}>Learn more...</button>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href=''>Create by Deondre English</a>
      </footer>
    </div>
  )
}

export default Home
