import React from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import InfoCard from '../components/HomePage/infocard'
import styles from '../styles/Home.module.css'


const globalState = {
  title : '',
};

const globalStateContext = React.createContext(globalState);

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Software Sparks</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <h1 className='text-3xl'>Welcome to the page</h1>
        <div className='grid grid-cols-4 gap-6 pt-12'>
          <InfoCard className='bg-red-300 w-64 h-48 p-4 border-red-400 rounded-xl hover:bg-red-500'>
            <p className='text-black text-1xl text-center'>Welcome to the project</p>
          </InfoCard>
          <InfoCard className='bg-red-300 w-64 h-48 p-4 border-red-400 rounded-xl hover:bg-red-500'>
            <p className='text-black text-1xl text-center'>Welcome to the project</p>
          </InfoCard>
          <InfoCard className='bg-red-300 w-64 h-48 p-4 border-red-400 rounded-xl hover:bg-red-500'>
            <p className='text-black text-1xl text-center'>Welcome to the project</p>
          </InfoCard>
          <InfoCard className='bg-red-300 w-64 h-48 p-4 border-red-400 rounded-xl hover:bg-red-500'>
            <p className='text-black text-1xl text-center'>Welcome to the project</p>
          </InfoCard>
        </div>
      </main> 
      
    </div>
  )
}

export default Home
