import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'

import Logo from '../public/logo.svg';

const Home: NextPage = () => {
  const top = `${styles.side} ${styles.top}`;
  const left = `${styles.side} ${styles.left}`;
  const front = `${styles.side} ${styles.front}`;

  return (
    <div>
      <Head>
        <title>Software Sparks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>

      <main  className={styles.container}> 
        <div className='flex'>
          <Image src={Logo} alt='Working dev...' width={64} height={1} />
          <h1 className={styles.pageheading}>Software Sparks</h1>
          <button className={styles.signinbutton}>Sign in</button>
        </div>
        {/* 3d cube Of programing languages */}
        <div className='grid grid-cols-2'>
          <div className={styles.cube}>
            <div className={top}></div>
            <div className={left}></div>
            <div className={front}></div>
          </div>
          <div></div> 
        </div>
        {/* Editor Example */}
        <div className='grid bg-slate-800 grid-cols-2 p-8 mb-12'>
          <div className='grid grid-cols-2'>
            <h2 className='font-sans text-2xl text-center'>Push this button to run the code</h2>
            <button className='p-0 bg-slate-200 w-24 h-8 rounded-md text-black hover:text-white'>Button</button>
            <button className='p-0 bg-slate-200 w-24 h-8 rounded-md text-black hover:text-white'>Settings</button>
          </div>
          <textarea className='w-full h-32 text-black'></textarea>
        </div>

        <div className='text-3xl'>
          <div className='text-center grid grid-cols-3 gap-4'>
            <div className={styles.gridcontainer}>
              <h1 className={styles.heading}>
                Create the unfathomable
              </h1>
              <p className={styles.content}>
                Create porjects that will change the world... Never underestimate the power of a single `Hello World`. This project aims to show developers they are not limited by their skill level. Just hit create new project if you get stuck the classes are there to help.
              </p>
              <button className={styles.button}>Learn more...</button>
            </div>
            <div className={styles.gridcontainer}>
              <h1 className={styles.heading}>
                No limits in development
              </h1>
              <p className={styles.content}>
                Our new code editing expirence will change the speed in which you code. No more waiting for the compiler. Create your own custom editor with our new editor API. Or, use the one we have created and allow yourself to customize it to your exact liking.
              </p>
              <button className={styles.button}>Learn more...</button>
            </div>
            <div className={styles.gridcontainer}>
              <h1 className={styles.heading}>
                Understand at a high level
              </h1>
              <p className={styles.content}>
                Our available classes allow you to understand the programming language at a high level. To develope huge applications you need to understand the language you are using. Our classes will help you understand the language and how to use it to create the next big thing.
              </p>
              <button className={styles.button}>Learn more...</button>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href=''>Create by Deondre English</a>
      </footer>
    </div>
  )
}

export default Home
