version: '3.1'

services:

  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: software-sparks
    

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080